# ==============================================================================
# Makefile for tinyMap - Lightweight Map Rendering Library using tinyGraphics
# ==============================================================================

CC       ?= gcc
AR       ?= ar
ARFLAGS   = rcs

# Directories
SRC_DIR       = src
INC_DIR       = include
VENDOR_DIR    = src/vendor/tinyGraphics
BUILD_DIR     = build
OBJ_DIR       = $(BUILD_DIR)/obj
LIB_DIR       = $(BUILD_DIR)/lib
BIN_DIR       = $(BUILD_DIR)/bin
EXAMPLES_DIR  = examples
TESTS_DIR     = tests

# Output Libraries
STATIC_LIB    = $(LIB_DIR)/libtinymap.a
SHARED_LIB    = $(LIB_DIR)/libtinymap.so

# Include paths
INCLUDES      = -I$(INC_DIR) \
                -I$(SRC_DIR) \
                -I$(VENDOR_DIR) \
                -I$(VENDOR_DIR)/src \
                -I$(VENDOR_DIR)/src/vendor/fast_obj

# Compiler and Linker flags
CFLAGS       ?= -Wall -Wextra -O2
CFLAGS       += $(INCLUDES) -fPIC -MMD -MP
LDFLAGS      ?= 
LIBS          = -lm -lglfw -lGL

# Source discovery
TM_SRCS       = $(wildcard $(SRC_DIR)/*.c)
TG_SRCS       = $(VENDOR_DIR)/graphics.c \
                $(VENDOR_DIR)/scene_context.c \
                $(wildcard $(VENDOR_DIR)/src/*.c) \
                $(wildcard $(VENDOR_DIR)/src/events/*.c) \
                $(wildcard $(VENDOR_DIR)/src/math/*.c) \
                $(wildcard $(VENDOR_DIR)/src/utils/*.c) \
                $(wildcard $(VENDOR_DIR)/src/2D/*.c) \
                $(wildcard $(VENDOR_DIR)/src/3D/*.c)

ALL_SRCS      = $(TM_SRCS) $(TG_SRCS)

# Object files corresponding to sources
TM_OBJS       = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/tm/%.o, $(TM_SRCS))
TG_OBJS       = $(patsubst $(VENDOR_DIR)/%.c, $(OBJ_DIR)/tg/%.o, $(TG_SRCS))
ALL_OBJS      = $(TM_OBJS) $(TG_OBJS)

# Dependency files generated by -MMD
DEPS          = $(ALL_OBJS:.o=.d)

# Default target
.PHONY: all static shared examples test clean help run run_opengl

all: static shared examples

# Static Library Target
static: $(STATIC_LIB)

$(STATIC_LIB): $(ALL_OBJS) | $(LIB_DIR)
	@echo "[AR] Creating static library: $@"
	@$(AR) $(ARFLAGS) $@ $^

# Shared Library Target
shared: $(SHARED_LIB)

$(SHARED_LIB): $(ALL_OBJS) | $(LIB_DIR)
	@echo "[CC] Creating shared library: $@"
	@$(CC) -shared $(LDFLAGS) -o $@ $^ -lm

# Object compilation rules for tinyMap sources
$(OBJ_DIR)/tm/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@echo "[CC] $<"
	@$(CC) $(CFLAGS) -c $< -o $@

# Object compilation rules for tinyGraphics vendor sources
$(OBJ_DIR)/tg/%.o: $(VENDOR_DIR)/%.c
	@mkdir -p $(dir $@)
	@echo "[CC] $<"
	@$(CC) $(CFLAGS) -c $< -o $@

# Directory creation helpers
$(LIB_DIR) $(BIN_DIR):
	@mkdir -p $@

# Examples Target (OpenGL Demo)
examples: $(BIN_DIR)/demo_opengl

$(BIN_DIR)/demo_opengl: $(EXAMPLES_DIR)/demo_opengl.c $(STATIC_LIB) | $(BIN_DIR)
	@echo "[CC] Building $@"
	@$(CC) $(CFLAGS) $< $(STATIC_LIB) $(LDFLAGS) $(LIBS) -o $@

# Test Suite Target
test: $(BIN_DIR)/test_tinymap
	@echo "Running tinyMap test suite..."
	@./$(BIN_DIR)/test_tinymap

$(BIN_DIR)/test_tinymap: $(TESTS_DIR)/test_tinymap.c $(STATIC_LIB) | $(BIN_DIR)
	@echo "[CC] Building test runner: $@"
	@$(CC) $(CFLAGS) $< $(STATIC_LIB) $(LDFLAGS) $(LIBS) -o $@

# Convenience run target
run: run_opengl

run_opengl: $(BIN_DIR)/demo_opengl
	@./$(BIN_DIR)/demo_opengl

# Clean build artifacts
clean:
	@echo "[CLEAN] Removing $(BUILD_DIR)/"
	@rm -rf $(BUILD_DIR)

# Help / Usage documentation
help:
	@echo "Available targets in tinyMap Makefile:"
	@echo "  all          - Build static library, shared library, and OpenGL demo (default)"
	@echo "  static       - Build static library ($(STATIC_LIB))"
	@echo "  shared       - Build shared library ($(SHARED_LIB))"
	@echo "  examples     - Build OpenGL demo ($(BIN_DIR)/demo_opengl)"
	@echo "  test         - Build and run unit tests"
	@echo "  run / run_opengl - Run the OpenGL map demo"
	@echo "  clean        - Remove all build artifacts"
	@echo "  help         - Show this help message"

# Include dependency files if they exist
-include $(DEPS)
